import type { Metadata } from "next";
import Galaxy from "@/components/react-bits/galaxy";

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className="min-w- h-dvh min-h-dvh w-screen max-w-screen bg-black lg:max-h-dvh lg:overflow-y-hidden">
        <Galaxy mouseRepulsion={false} mouseInteraction={false} />
        {children}
      </body>
    </html>
  );
}
