/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PortfolioRouteRouteImport } from './routes/_portfolio/route'
import { Route as PortfolioIndexRouteImport } from './routes/_portfolio/index'
import { Route as PortfolioContactarRouteImport } from './routes/_portfolio/contactar'
import { Route as PortfolioWith_back_buttonRouteRouteImport } from './routes/_portfolio/_with_back_button/route'
import { Route as PortfolioWith_back_buttonExperienciaRouteImport } from './routes/_portfolio/_with_back_button/experiencia'

const PortfolioRouteRoute = PortfolioRouteRouteImport.update({
  id: '/_portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioIndexRoute = PortfolioIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortfolioRouteRoute,
} as any)
const PortfolioContactarRoute = PortfolioContactarRouteImport.update({
  id: '/contactar',
  path: '/contactar',
  getParentRoute: () => PortfolioRouteRoute,
} as any)
const PortfolioWith_back_buttonRouteRoute =
  PortfolioWith_back_buttonRouteRouteImport.update({
    id: '/_with_back_button',
    getParentRoute: () => PortfolioRouteRoute,
  } as any)
const PortfolioWith_back_buttonExperienciaRoute =
  PortfolioWith_back_buttonExperienciaRouteImport.update({
    id: '/experiencia',
    path: '/experiencia',
    getParentRoute: () => PortfolioWith_back_buttonRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PortfolioIndexRoute
  '/contactar': typeof PortfolioContactarRoute
  '/experiencia': typeof PortfolioWith_back_buttonExperienciaRoute
}
export interface FileRoutesByTo {
  '/': typeof PortfolioIndexRoute
  '/contactar': typeof PortfolioContactarRoute
  '/experiencia': typeof PortfolioWith_back_buttonExperienciaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_portfolio': typeof PortfolioRouteRouteWithChildren
  '/_portfolio/_with_back_button': typeof PortfolioWith_back_buttonRouteRouteWithChildren
  '/_portfolio/contactar': typeof PortfolioContactarRoute
  '/_portfolio/': typeof PortfolioIndexRoute
  '/_portfolio/_with_back_button/experiencia': typeof PortfolioWith_back_buttonExperienciaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/contactar' | '/experiencia'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/contactar' | '/experiencia'
  id:
    | '__root__'
    | '/_portfolio'
    | '/_portfolio/_with_back_button'
    | '/_portfolio/contactar'
    | '/_portfolio/'
    | '/_portfolio/_with_back_button/experiencia'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PortfolioRouteRoute: typeof PortfolioRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_portfolio': {
      id: '/_portfolio'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PortfolioRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_portfolio/': {
      id: '/_portfolio/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PortfolioIndexRouteImport
      parentRoute: typeof PortfolioRouteRoute
    }
    '/_portfolio/contactar': {
      id: '/_portfolio/contactar'
      path: '/contactar'
      fullPath: '/contactar'
      preLoaderRoute: typeof PortfolioContactarRouteImport
      parentRoute: typeof PortfolioRouteRoute
    }
    '/_portfolio/_with_back_button': {
      id: '/_portfolio/_with_back_button'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PortfolioWith_back_buttonRouteRouteImport
      parentRoute: typeof PortfolioRouteRoute
    }
    '/_portfolio/_with_back_button/experiencia': {
      id: '/_portfolio/_with_back_button/experiencia'
      path: '/experiencia'
      fullPath: '/experiencia'
      preLoaderRoute: typeof PortfolioWith_back_buttonExperienciaRouteImport
      parentRoute: typeof PortfolioWith_back_buttonRouteRoute
    }
  }
}

interface PortfolioWith_back_buttonRouteRouteChildren {
  PortfolioWith_back_buttonExperienciaRoute: typeof PortfolioWith_back_buttonExperienciaRoute
}

const PortfolioWith_back_buttonRouteRouteChildren: PortfolioWith_back_buttonRouteRouteChildren =
  {
    PortfolioWith_back_buttonExperienciaRoute:
      PortfolioWith_back_buttonExperienciaRoute,
  }

const PortfolioWith_back_buttonRouteRouteWithChildren =
  PortfolioWith_back_buttonRouteRoute._addFileChildren(
    PortfolioWith_back_buttonRouteRouteChildren,
  )

interface PortfolioRouteRouteChildren {
  PortfolioWith_back_buttonRouteRoute: typeof PortfolioWith_back_buttonRouteRouteWithChildren
  PortfolioContactarRoute: typeof PortfolioContactarRoute
  PortfolioIndexRoute: typeof PortfolioIndexRoute
}

const PortfolioRouteRouteChildren: PortfolioRouteRouteChildren = {
  PortfolioWith_back_buttonRouteRoute:
    PortfolioWith_back_buttonRouteRouteWithChildren,
  PortfolioContactarRoute: PortfolioContactarRoute,
  PortfolioIndexRoute: PortfolioIndexRoute,
}

const PortfolioRouteRouteWithChildren = PortfolioRouteRoute._addFileChildren(
  PortfolioRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  PortfolioRouteRoute: PortfolioRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
