/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PortfolioRouteRouteImport } from './routes/_portfolio/route'
import { Route as PortfolioIndexRouteImport } from './routes/_portfolio/index'
import { Route as PortfolioContactarRouteImport } from './routes/_portfolio/contactar'

const PortfolioRouteRoute = PortfolioRouteRouteImport.update({
  id: '/_portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioIndexRoute = PortfolioIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortfolioRouteRoute,
} as any)
const PortfolioContactarRoute = PortfolioContactarRouteImport.update({
  id: '/contactar',
  path: '/contactar',
  getParentRoute: () => PortfolioRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PortfolioIndexRoute
  '/contactar': typeof PortfolioContactarRoute
}
export interface FileRoutesByTo {
  '/contactar': typeof PortfolioContactarRoute
  '/': typeof PortfolioIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_portfolio': typeof PortfolioRouteRouteWithChildren
  '/_portfolio/contactar': typeof PortfolioContactarRoute
  '/_portfolio/': typeof PortfolioIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/contactar'
  fileRoutesByTo: FileRoutesByTo
  to: '/contactar' | '/'
  id: '__root__' | '/_portfolio' | '/_portfolio/contactar' | '/_portfolio/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PortfolioRouteRoute: typeof PortfolioRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_portfolio': {
      id: '/_portfolio'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PortfolioRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_portfolio/': {
      id: '/_portfolio/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PortfolioIndexRouteImport
      parentRoute: typeof PortfolioRouteRoute
    }
    '/_portfolio/contactar': {
      id: '/_portfolio/contactar'
      path: '/contactar'
      fullPath: '/contactar'
      preLoaderRoute: typeof PortfolioContactarRouteImport
      parentRoute: typeof PortfolioRouteRoute
    }
  }
}

interface PortfolioRouteRouteChildren {
  PortfolioContactarRoute: typeof PortfolioContactarRoute
  PortfolioIndexRoute: typeof PortfolioIndexRoute
}

const PortfolioRouteRouteChildren: PortfolioRouteRouteChildren = {
  PortfolioContactarRoute: PortfolioContactarRoute,
  PortfolioIndexRoute: PortfolioIndexRoute,
}

const PortfolioRouteRouteWithChildren = PortfolioRouteRoute._addFileChildren(
  PortfolioRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  PortfolioRouteRoute: PortfolioRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
